name: Main CI
run-name: Run ${{ github.run_id }} of branch ${{ github.event.pull_request.head.ref || github.ref_name }}

on:
  { push }

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    if: github.event.review.state == 'APPROVED' || github.event.pull_request.merged == true || github.event_name == 'push'
    uses: ./.github/workflows/pr_checker.yml
    secrets: inherit